from datetime import datetime, timezone
from typing import Literal, Optional
from uuid import UUID

from schemas.rag import SourceReference

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Payload received from the client."""

    message: str = Field(
        ..., description="The raw input message from the user.", min_length=1
    )
    role: str = "user"
    conversation_id: UUID = Field(
        ...,
        alias="conversationId",
        description="Database conversation thread identifier.",
    )

    model_config = {
        "populate_by_name": True,
        "json_schema_extra": {
            "example": {
                "message": "Tell me a short story about an AI agent.",
                "conversationId": "550e8400-e29b-41d4-a716-446655440000",
            }
        },
    }


class MessageParam(BaseModel):
    """Represents an individual chat turn stored in memory."""

    role: Literal["user", "model"] = Field(
        ...,
        description="The author of this message turn. Gemini uses 'model' for the assistant.",
    )
    content: str = Field(..., description="The textual content of the message.")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    token_count: Optional[int] = Field(
        None,
        alias="tokenCount",
        description="Pre-calculated token count for fast sliding-window budget checks.",
    )

    model_config = {"populate_by_name": True}


class ChatStreamDelta(BaseModel):
    """The inner data content payload of an individual SSE stream chunk."""

    content: str = Field(
        default="",
        description="The token/text fragment generated by the Gemini engine.",
    )
    finish_reason: Optional[str] = Field(
        None,
        alias="finishReason",
        description="Indicates completion status (e.g., 'STOP', 'MAX_TOKENS') on the final chunk.",
    )
    sources: Optional[list["SourceReference"]] = Field(
        None,
        description="List of cited documents when running the RAG route.",
    )

    model_config = {"populate_by_name": True}


class ChatStreamResponse(BaseModel):
    """The top-level envelope schema sent down the SSE pipe."""

    success: bool = Field(
        default=True,
        description="Status flag matching your global error payload pattern.",
    )
    data: ChatStreamDelta = Field(
        ..., description="The data chunk containing the token delta or metadata."
    )

    model_config = {"populate_by_name": True}
