"""Add pending Jira tickets

Revision ID: 9db8d2a36591
Revises: d8e9f0a1b2c3
Create Date: 2026-06-19 14:07:04.476914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db8d2a36591'
down_revision: Union[str, Sequence[str], None] = 'd8e9f0a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_jira_tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_jira_tickets_status'), 'pending_jira_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_pending_jira_tickets_user_id'), 'pending_jira_tickets', ['user_id'], unique=False)
    op.drop_index(op.f('ix_session_token'), table_name='session')
    op.create_index(op.f('ix_session_refresh_token'), 'session', ['refresh_token'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_session_refresh_token'), table_name='session')
    op.create_index(op.f('ix_session_token'), 'session', ['refresh_token'], unique=True)
    op.drop_index(op.f('ix_pending_jira_tickets_user_id'), table_name='pending_jira_tickets')
    op.drop_index(op.f('ix_pending_jira_tickets_status'), table_name='pending_jira_tickets')
    op.drop_table('pending_jira_tickets')
    # ### end Alembic commands ###
